import React from 'react'

export default function Projects() {
  return (
    <div  >
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum minus quas veniam officiis tempora odit ipsa recusandae! Praesentium ratione mollitia vel molestias nulla? Libero maiores sed, architecto aliquid enim nam?
    </div>
  )
}
